# Generated by Django 3.2.6 on 2022-01-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blango_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
